version: '3.4'

services:

    discord:
        image: automatedtestingservice/discord
        container_name: discord
        build:
            context: .
            dockerfile: Dockerfile-discord
