FROM docker/compose:debian-1.27.4

ADD app /host/app
WORKDIR /host/app

RUN mkdir /host/tmp
RUN apt update

# install python
RUN apt install gpg-agent software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3

# install dependencies
RUN apt install python3-pip -y
RUN pip3 install --upgrade python-dateutil

ENTRYPOINT ["python3", "entrypoint.py"]