version: '3.4'


services:

    discord:
        image: envomp/discord-data-fetcher
        privileged: true # summons docker container for each channel
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /analyzer/discord-output/:/analyzer/discord-output/
            - /analyzer/env:/analyzer/app/.env
#            - /analyzer/app/:/analyzer/app/ # For developing
