FROM docker/compose:debian-1.27.4

ADD app /host/app
WORKDIR /host/app

RUN mkdir /host/tmp
RUN apt update

# Set locale
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LANG en_US.UTF-8

# install python
RUN apt install gpg-agent software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3

# install dependencies
RUN apt install python3-pip -y
RUN pip3 install --upgrade python-dateutil

ENTRYPOINT ["python3", "-u", "entrypoint.py"]