version: '3.4'

services:

    guilds_fetcher:
        image: tyrrrz/discordchatexporter:stable
        restart: "no"
        env_file:
            - /analyzer/app/.env
        entrypoint: [ "dotnet", "/app/DiscordChatExporter.Cli.dll", "guilds" ]
